// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8EoVH9-MC3smOnrm21o848GhPQFy7N2s',
    appId: '1:1040266212584:web:c3d8f625575627f25fc55d',
    messagingSenderId: '1040266212584',
    projectId: 'project-firebase-d8be2',
    authDomain: 'project-firebase-d8be2.firebaseapp.com',
    storageBucket: 'project-firebase-d8be2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo0DcKD1J-xj4YsZKR2ucleN2v0b2VApc',
    appId: '1:1040266212584:android:d61a852a983e54e55fc55d',
    messagingSenderId: '1040266212584',
    projectId: 'project-firebase-d8be2',
    storageBucket: 'project-firebase-d8be2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjuYvuS639hsp0cOnlzbmh-09v5x7wQUQ',
    appId: '1:1040266212584:ios:3930a16e1ca9e90a5fc55d',
    messagingSenderId: '1040266212584',
    projectId: 'project-firebase-d8be2',
    storageBucket: 'project-firebase-d8be2.appspot.com',
    iosBundleId: 'com.example.projectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjuYvuS639hsp0cOnlzbmh-09v5x7wQUQ',
    appId: '1:1040266212584:ios:28779c1b6c4726705fc55d',
    messagingSenderId: '1040266212584',
    projectId: 'project-firebase-d8be2',
    storageBucket: 'project-firebase-d8be2.appspot.com',
    iosBundleId: 'com.example.projectFirebase.RunnerTests',
  );
}
